name: flutter_application_hello
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.2
  dio: ^5.4.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  auto_route: ^7.8.4
  flutter_lints: ^3.0.1
  shared_preferences: ^2.2.2
  flutter_flipperkit: ^0.0.29
  json_serializable: ^6.7.1
  flutter_spinkit: ^5.2.0
  uuid: ^3.0.7
  cached_network_image: ^3.3.1
  crypto: ^3.0.3
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  custom_lint:
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
